### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by alekseynemiro** [alekseynemiro/tapplayer#89]
Error during automatic testing: `Object reference not set to an instance of an object at TapPlayer.Maui.Components.ProjectEdit.MainScrollView_SizeChanged`.

## Affected versions
- v1.4 (20230608)

## Device (please complete the following information):
- Android 12L (SDK 32)

```
Exception Process: ru.nemiro.apps.tapplayer, PID: 10484
android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
   at TapPlayer.Maui.Components.ProjectEdit.MainScrollView_SizeChanged(Object sender, EventArgs e)
   at Microsoft.Maui.Controls.VisualElement.UpdateBoundsComponents(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.set_Frame(Rect value)
   at Microsoft.Maui.Controls.ScrollView.ArrangeOverride(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
   at Microsoft.Maui.Controls.Compatibility.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rect region)
   at Microsoft.Maui.Controls.TemplatedView.LayoutChildren(Double x, Double y, Double width, Double height)
   at Microsoft.Maui.Controls.Compatibility.Layout.UpdateChildrenLayout()
   at Microsoft.Maui.Controls.Compatibility.Layout.OnSizeAllocated(Double width, Double height)
   at Microsoft.Maui.Controls.VisualElement.SizeAllocated(Double width, Double height)
   at Microsoft.Maui.Controls.VisualElement.UpdateBoundsComponents(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.set_Frame(Rect value)
   at Microsoft.Maui.Controls.TemplatedView.ArrangeOverride(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
   at Microsoft.Maui.Controls.Compatibility.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rect region)
   at Microsoft.Maui.Controls.Page.LayoutChildren(Double x, Double y, Double width, Double height)
   at Microsoft.Maui.Controls.Page.UpdateChildrenLayout()
   at Microsoft.Maui.Controls.Page.OnSizeAllocated(Double width, Double height)
   at Microsoft.Maui.Controls.VisualElement.SizeAllocated(Double width, Double height)
   at Microsoft.Maui.Controls.VisualElement.UpdateBoundsComponents(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.set_Frame(Rect value)
   at Microsoft.Maui.Controls.ContentPage.Microsoft.Maui.IContentView.CrossPlatformArrange(Rect bounds)
   at Microsoft.Maui.Platform.ContentViewGroup.OnLayout(Boolean changed, Int32 left, Int32 top, Int32 right, Int32 bottom)
   at Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr , IntPtr , Boolean , Int32 , Int32 , Int32 , Int32 )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V , IntPtr , IntPtr , Boolean , Int32 , Int32 , Int32 , Int32 )
--- End of stack trace from previous location ---
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference , JniObjectReference , JniMethodInfo , JniArgumentValue* )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
   at Android.Views.ViewGroup.Layout(Int32 , Int32 , Int32 , Int32 )
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellPageContainer.OnLayout(Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b)
   at Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr , IntPtr , Boolean , Int32 , Int32 , Int32 , Int32 )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V , IntPtr , IntPtr , Boolean , Int32 , Int32 , Int32 , Int32 )
  at crc640ec207abc449b2ca.ShellPageContainer.n_onLayout
  at crc640ec207abc449b2ca.ShellPageContainer.onLayout (ShellPageContainer.java:58)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild (HeaderScrollingViewBehavior.java:149)
  at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild (ViewOffsetBehavior.java:43)
  at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild (AppBarLayout.java:2253)
  at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout (CoordinatorLayout.java:953)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at android.widget.LinearLayout.setChildFrame (LinearLayout.java:1829)
  at android.widget.LinearLayout.layoutVertical (LinearLayout.java:1673)
  at android.widget.LinearLayout.onLayout (LinearLayout.java:1582)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at androidx.drawerlayout.widget.DrawerLayout.onLayout (DrawerLayout.java:1263)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at android.widget.LinearLayout.setChildFrame (LinearLayout.java:1829)
  at android.widget.LinearLayout.layoutHorizontal (LinearLayout.java:1818)
  at android.widget.LinearLayout.onLayout (LinearLayout.java:1584)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at android.widget.LinearLayout.setChildFrame (LinearLayout.java:1829)
  at android.widget.LinearLayout.layoutVertical (LinearLayout.java:1673)
  at android.widget.LinearLayout.onLayout (LinearLayout.java:1582)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at com.android.internal.widget.DecorCaptionView.onLayout (DecorCaptionView.java:334)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at com.android.internal.policy.DecorView.onLayout (DecorView.java:797)
  at android.view.View.layout (View.java:23203)
  at android.view.ViewGroup.layout (ViewGroup.java:6412)
  at android.view.ViewRootImpl.performLayout (ViewRootImpl.java:3749)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3205)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2179)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8787)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1037)
  at android.view.Choreographer.doCallbacks (Choreographer.java:845)
  at android.view.Choreographer.doFrame (Choreographer.java:780)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1022)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7870)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)
```

**Comment by alekseynemiro** [comment]
Fixed in v1.4.
